apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-activemq-0
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: slow
  nfs: 
    path: /opt/mqdata/activemq-0
    server: 192.168.7.206 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-activemq-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /opt/mqdata/activemq-1
    server: 192.168.7.206
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-activemq-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /opt/mqdata/activemq-2
    server: 192.168.7.206
    readOnly: false
