apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-activemq-0 
spec:
  accessModes:
  - ReadWriteOnce      
  storageClassName: slow
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-activemq-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-activemq-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  resources:
     requests:
       storage: 10Gi
