apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-0
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: slow
  nfs: 
    path: /opt/zkdata/zk-data-0 
    server: 192.168.7.206 
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /opt/zkdata/zk-data-1
    server: 192.168.7.206
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /opt/zkdata/zk-data-2
    server: 192.168.7.206
    readOnly: false
